name: Upstream Sync

on:
  schedule:
    - cron: '0 2 * * *' # 每天北京时间上午10点执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Syncing help
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git remote add upstream https://github.com/caidaoli/CLIProxyAPI.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
